name: "helloworld workflow"

#controls when the action will run.concurrency:
#Triggers the workflow on push done to master or production branch

on:
    push:
        branches: ["*"]
jobs:
    hello_world:
        runs-on: ubuntu-latest
        steps:
            - name: "print hello world"
              run: echo "hello world"
            - name: "Print current date"
              run: date
            - name: "Print the run run"
              run: echo "Runing"
