name: "Multi event pipeline / workflow" #name of the pipeline
on:
  push: #Event Whenener a push is made to the repository on the main branch
      branches:
          - main
  pull_request: #Event: Whenever a pull request is made to the repository
      branches:
          - main
          - test
      types:
          - closed
  


jobs:
    on-push: #job 1
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps: #steps to be executed in the job
            - name: "Running on master push"
              run: echo "Running on master push"
    on-pull-request: #job 2
        if: github.event_name == 'pull'
        runs-on: ubuntu-latest
        steps: #steps to be executed in the job
            - name: "Running on pull request"
              run: echo "Running on pull request"
    on-pull-request-closed:
        if: github.event_name == 'pull_request closed'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request closed"
              run: echo "Running on pull request closed"


